name: Build WarHams

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore WarHams.csproj

    - name: Build Plugin
      run: msbuild WarHams.csproj /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WarHams-Plugin
        path: bin/Release/net48/WarHams.dll
