name: Build WarHams

on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore WarHams.csproj

    - name: Build
      run: msbuild WarHams.csproj /p:Configuration=Release /p:TargetFramework=net48

    - name: Upload DLL
      uses: actions/upload-artifact@v4
      with:
        name: WarHams-Release
        path: bin/Release/net48/WarHams.dll
